This notebook contains some of my notes for week 2's videos, followed by the programming assignment. 

Video 1. 
m training examples $ = (x^1,y^1), (x^2,y^2), (x^m,y^m) $

In [1]:
# GRADED FUNCTION: basic_sigmoid

import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1 + math.exp(-x))
    ### END CODE HERE ###
    
    return s

basic_sigmoid(3)


0.9525741268224334

In [2]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))


[ 2.71828183  7.3890561  20.08553692]


In [16]:
#example of vectorized dot product. Sum of element-wise products. 
w = np.array(range(1,5))
print(w)
x = np.array(range(1,5))
print("X values = " + str(x))
y = np.dot(w,x)
print("Dot product = " + str(y))

y = 2 * x
print("Two multiplied by x vector = " + str(y))


[1 2 3 4]
X values = [1 2 3 4]
Dot product = 30
Two multiplied by x vector = [2 4 6 8]


## Python vectorization.
### Video 2. 
### Matrix multiplication

Latex is formatted correctly in a local jupyter notebook, and github does render it! See example.

$$\LaTeX$$

$$E = mc^{2}$$ 

In [3]:
# GRADED FUNCTION: sigmoid

import numpy as np # this means you can access numpy functions by writing np.function() instead of numpy.function()

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s =  1/(1 + np.exp(-x))
    ### END CODE HERE ###
    
    return s

x = np.array([1, 2, 3])
sigmoid(x)


array([0.73105858, 0.88079708, 0.95257413])

In [4]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    s = sigmoid(x)
    ds = s*(1-s)
    ### END CODE HERE ###
    
    return ds

x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]
